Repository codersforcauses/poops, pull requests merged in 2022-07, with the labels that each got.

#60 I57 requires user signin to access the pages
  .env
  package-lock.json
  package.json
  public/images/poops-logo.jpg
  src/components/Firebase/init.ts
  src/components/PrivateRoute/index.tsx
  src/context/AuthContext.tsx
  src/pages/_app.tsx
  src/pages/contact.tsx
  src/pages/incidents.tsx
  src/pages/index.tsx
  src/pages/login.tsx
  src/pages/profile.tsx
  src/pages/visit.tsx
  yarn.lock
Labels: backend

#56 I24 integrate firebase authentication to sign in sign up and forget password forms
  public/images/poops-logo-transparent.png
  src/components/Login/LoginButton.tsx
  src/components/Login/LoginPanel.tsx
  src/context/AuthContext.tsx
  src/pages/login.tsx
  tailwind.config.js
Labels: backend

#49 I27 create a contact page
  .husky/pre-commit
  mockData/CONTACT_DATA.json
  mockData/PROFILE_DATA.json
  package-lock.json
  package.json
  public/favicon/manifest.json
  src/components/Contact/avatar.tsx
  src/components/Contact/contactform.tsx
  src/components/Contact/contactinfo.tsx
  src/components/Contact/contactitem.tsx
  src/components/Contact/contactlist.tsx
  src/components/Contact/profileitem.tsx
  src/components/Contact/regiondropdown.tsx
  src/components/Contact/tagdropdown.tsx
  src/components/SearchBar/searchbar.tsx
  src/components/SearchBar/searchtag.tsx
  src/pages/contact.tsx
  src/pages/contact/[id].tsx
  src/pages/contact/index.tsx
  src/types/types.ts
  tailwind.config.js
  yarn.lock
Labels: frontend

#85 i84 - Replaced grey w/ colors.gray
  src/components/Contact/contactform.tsx
  src/components/Contact/contactinfo.tsx
  src/components/Contact/contactitem.tsx
  src/components/Contact/profileitem.tsx
  src/components/Login/LoginButton.tsx
  src/pages/contact/index.tsx
  tailwind.config.js
Labels: frontend, design

#107 I106 contacts not displaying tags
  src/components/Contact/contactform.tsx
  src/components/Contact/contactinfo.tsx
Labels: bug, frontend

#109 i108 Standardise commute method for visit page
  src/components/Visit/commuteselector.tsx
Labels: frontend
